"use client";

import { Tweak } from "@prisma/client";
import Image from "next/image";
import { Button } from "@/components/ui/button";
import {
  Download,
  Eye,
  Star,
  ChevronUp,
  Hash,
  FileCode,
  Calendar,
  Loader2,
  Heart,
} from "lucide-react";
import { useEffect, useState } from "react";
import { incrementTweakViews } from "@/actions/tweaks";
import { Sheet, SheetTrigger, SheetContent } from "@/components/ui/sheet";
import { useMediaQuery } from "@/hooks/useMediaQuery";
import { formatDistanceToNow } from "date-fns";
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import CustomBreadCrump from "@/components/CustomBreadCrump";
import { TweaksService } from "@/app/(dashboard)/_services/tweaksService";
import { useRouter } from "next/navigation";
import toast from "react-hot-toast";
import { cn } from "@/lib/utils";

interface TweakHeaderProps {
  tweak: Tweak;
  categoryName: string;
  userId: string | null;
}

export default function TweakHeader({
  tweak,
  categoryName,
  userId,
}: TweakHeaderProps) {
  const isMobile = useMediaQuery("(max-width: 768px)");
  const router = useRouter();
  const [isLoading, setIsLoading] = useState(false);
  const [isDownloading, setIsDownloading] = useState(false);
  const isFavorited = tweak.savedUsers.includes(userId || "");

  useEffect(() => {
    incrementTweakViews(tweak.id);
  }, [tweak.id]);

  const handleFavorite = async () => {
    if (!userId) {
      toast.error("Please sign in to save tweaks");
      return;
    }

    try {
      setIsLoading(true);
      const result = await TweaksService.toggleSaveTweak(tweak.id);

      if (result.error) {
        toast.error(result.error);
        return;
      }

      toast.success(
        isFavorited ? "Removed from favorites" : "Added to favorites"
      );
      router.refresh();
    } catch (error) {
      toast.error("Failed to update favorite status");
    } finally {
      setIsLoading(false);
    }
  };

  const handleDownload = async () => {
    try {
      setIsDownloading(true);

      // Get file extension from tweak type
      const fileExt =
        tweak.tweak_type?.toLowerCase() === "batch" ? ".bat" : ".reg";

      // Create warning message based on file type
      const warningMessage =
        fileExt === ".bat"
          ? `REM ⚠️ WARNING ⚠️\r\n\r\n` +
            `REM BetterPerformance is not responsible for any misuse of the tweaks generated by this website.\r\n` +
            `REM These tweaks are automatically created as soon as you click the "Download" button.\r\n\r\n` +
            `REM IMPORTANT:\r\n` +
            `REM Before applying any tweak, please make sure to create a restore point.\r\n` +
            `REM This will allow you to revert changes in case you are not satisfied with the before/after effects of the tweak.\r\n\r\n` +
            `REM The services offered by BetterPerformance are COMPLETELY FREE.\r\n` +
            `REM However, we appreciate any donations you may want to make to help maintain the website and ensure its continuity.\r\n\r\n` +
            `REM It is STRICTLY FORBIDDEN to sell any of the tweaks generated by this website\r\n` +
            `REM or to commercialize any service related to the use of this platform.\r\n` +
            `REM If it is proven that a user is violating this rule, the following actions will be taken:\r\n\r\n` +
            `REM     Permanent ban of the user to prevent future access to the website.\r\n` +
            `REM     Legal actions against the user, if applicable.\r\n\r\n` +
            `REM COPYRIGHT NOTICE:\r\n` +
            `REM All copyright rights are reserved by BetterPerformance.\r\n` +
            `REM While some elements of the tweaks may not be 100% original to the author,\r\n` +
            `REM their development is entirely managed and created by BetterPerformance.\r\n\r\n` +
            `REM Enjoy the service, use it responsibly, and don't forget to create a restore point! 🙌\r\n\r\n`
          : `Windows Registry Editor Version 5.00\r\n\r\n` +
            `; ⚠️ WARNING ⚠️\r\n\r\n` +
            `; BetterPerformance is not responsible for any misuse of the tweaks generated by this website.\r\n` +
            `; These tweaks are automatically created as soon as you click the "Download" button.\r\n\r\n` +
            `; IMPORTANT:\r\n` +
            `; Before applying any tweak, please make sure to create a restore point.\r\n` +
            `; This will allow you to revert changes in case you are not satisfied with the before/after effects of the tweak.\r\n\r\n` +
            `; The services offered by BetterPerformance are COMPLETELY FREE.\r\n` +
            `; However, we appreciate any donations you may want to make to help maintain the website and ensure its continuity.\r\n\r\n` +
            `; It is STRICTLY FORBIDDEN to sell any of the tweaks generated by this website\r\n` +
            `; or to commercialize any service related to the use of this platform.\r\n` +
            `; If it is proven that a user is violating this rule, the following actions will be taken:\r\n\r\n` +
            `;     Permanent ban of the user to prevent future access to the website.\r\n` +
            `;     Legal actions against the user, if applicable.\r\n\r\n` +
            `; COPYRIGHT NOTICE:\r\n` +
            `; All copyright rights are reserved by BetterPerformance.\r\n` +
            `; While some elements of the tweaks may not be 100% original to the author,\r\n` +
            `; their development is entirely managed and created by BetterPerformance.\r\n\r\n` +
            `; Enjoy the service, use it responsibly, and don't forget to create a restore point! 🙌\r\n\r\n`;

      // Create blob with warning and content
      const content = warningMessage + (tweak.regedit || "");
      const blob = new Blob([content], { type: "text/plain" });

      // Create download link
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = `${tweak.title}${fileExt}`;

      // Trigger download
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      window.URL.revokeObjectURL(url);

      // Increment download count
      const result = await TweaksService.incrementDownloadCount(tweak.id);
      if (result.error) {
        console.error("Failed to increment download count:", result.error);
      }

      toast.success("Download started");
      router.refresh();
    } catch (error) {
      toast.error("Failed to download tweak");
    } finally {
      setIsDownloading(false);
    }
  };

  if (isMobile) {
    return (
      <>
        <CustomBreadCrump
          breadCrumpPage={tweak.title}
          breadCrumpItem={[
            {
              link: "/explore",
              label: "Explore",
            },
          ]}
        />
        <Sheet>
          <SheetTrigger asChild>
            <Button
              size="lg"
              variant="outline"
              className="fixed bottom-6 left-1/2 -translate-x-1/2 z-50 rounded-full px-6 bg-background animate-pulse border-primary"
            >
              <ChevronUp className="h-4 w-4 mr-2" />
              More Info
            </Button>
          </SheetTrigger>
          <SheetContent side="bottom" className="h-[85vh] rounded-t-[10px]">
            <div className="space-y-6">
              {/* Header with Icon and Basic Info */}
              <div className="flex items-center gap-4">
                <div className="relative w-10 h-10 rounded-lg overflow-hidden bg-secondary/10">
                  <Image
                    src={tweak.icon_url || "/placeholder.svg"}
                    alt={tweak.title}
                    width={40}
                    height={40}
                    className="object-contain"
                  />
                </div>
                <div className="flex-1 min-w-0">
                  <h1 className="text-base font-medium">{tweak.title}</h1>
                  <p className="text-sm text-muted-foreground truncate">
                    {tweak.short_description}
                  </p>
                </div>
              </div>

              {/* Stats */}
              <div className="flex items-center gap-6 text-sm text-muted-foreground">
                <div className="flex items-center gap-1">
                  <Download className="h-4 w-4" />
                  <span>{tweak.downloadCount}</span>
                </div>
                <div className="flex items-center gap-1">
                  <Star className="h-4 w-4" />
                  <span>{tweak.savedUsers.length}</span>
                </div>
                <div className="flex items-center gap-1">
                  <Eye className="h-4 w-4" />
                  <span>{tweak.viewCount}</span>
                </div>
              </div>

              {/* Action Buttons */}
              <div className="flex gap-3">
                <Button
                  variant="outline"
                  className="flex-1"
                  onClick={handleFavorite}
                  disabled={isLoading}
                >
                  {isLoading ? (
                    <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  ) : (
                    <Heart
                      className={cn(
                        "h-4 w-4 mr-2",
                        isFavorited && "fill-current"
                      )}
                    />
                  )}
                  {isFavorited ? "Favorited" : "Favorite"}
                </Button>
                <Button
                  className="flex-1 bg-primary"
                  onClick={handleDownload}
                  disabled={isDownloading}
                >
                  {isDownloading ? (
                    <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  ) : (
                    <Download className="h-4 w-4 mr-2" />
                  )}
                  Download
                </Button>
              </div>

              {/* Additional Info */}
              <div className="space-y-6 pt-4">
                {/* Author Section */}
                <div className="flex items-center gap-3 p-3 rounded-lg bg-secondary/20">
                  <Avatar className="h-10 w-10">
                    <AvatarImage src="/placeholder-avatar.svg" />
                    <AvatarFallback>
                      {tweak.author?.[0]?.toUpperCase() || "A"}
                    </AvatarFallback>
                  </Avatar>
                  <div>
                    <div className="font-medium">
                      {tweak.author || "Anonymous"}
                    </div>
                    <div className="text-sm text-muted-foreground">Author</div>
                  </div>
                </div>

                {/* Details Grid */}
                <div className="space-y-4">
                  <div className="flex items-start gap-3">
                    <Hash className="h-4 w-4 text-primary mt-1" />
                    <div>
                      <div className="text-sm font-medium">Category</div>
                      <Badge variant="secondary" className="mt-1">
                        {categoryName || "Uncategorized"}
                      </Badge>
                    </div>
                  </div>

                  <div className="flex items-start gap-3">
                    <FileCode className="h-4 w-4 text-primary mt-1" />
                    <div>
                      <div className="text-sm font-medium">Type</div>
                      <Badge variant="outline" className="mt-1">
                        {tweak.tweak_type || "Not specified"}
                      </Badge>
                    </div>
                  </div>

                  <div className="flex items-start gap-3">
                    <Calendar className="h-4 w-4 text-primary mt-1" />
                    <div>
                      <div className="text-sm font-medium">Last Updated</div>
                      <div className="text-sm text-muted-foreground mt-1">
                        {formatDistanceToNow(new Date(tweak.updatedAt), {
                          addSuffix: true,
                        })}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </SheetContent>
        </Sheet>
      </>
    );
  }

  return (
    <>
      <CustomBreadCrump
        breadCrumpPage={tweak.title}
        breadCrumpItem={[
          {
            link: "/explore",
            label: "Explore",
          },
        ]}
      />
      <div className="fixed bottom-6 left-1/2 -translate-x-1/2 z-30 rounded-lg border shadow-lg bg-background/60 backdrop-blur-xl w-full max-w-2xl mx-4">
        <div className="px-6 py-4">
          <div className="flex gap-4">
            {/* Icon */}
            <div className="relative w-12 h-12 rounded-lg overflow-hidden bg-secondary/10 flex-shrink-0">
              <Image
                src={tweak.icon_url || "/placeholder.svg"}
                alt={tweak.title}
                width={48}
                height={48}
                className="object-contain"
              />
            </div>

            <div className="flex-1 min-w-0">
              {/* Title and Stats */}
              <div className="flex items-center justify-between">
                <h1 className="text-lg font-medium truncate">{tweak.title}</h1>
                <div className="flex items-center gap-4 text-sm text-muted-foreground">
                  <div className="flex items-center gap-1">
                    <Download className="h-4 w-4" />
                    <span>{tweak.downloadCount}</span>
                  </div>
                  <div className="flex items-center gap-1">
                    <Star className="h-4 w-4" />
                    <span>{tweak.savedUsers.length}</span>
                  </div>
                  <div className="flex items-center gap-1">
                    <Eye className="h-4 w-4" />
                    <span>{tweak.viewCount}</span>
                  </div>
                </div>
              </div>

              {/* Description */}
              <p className="text-sm text-muted-foreground truncate mt-1">
                {tweak.short_description}
              </p>
            </div>

            {/* Actions */}
            <div className="flex items-start gap-3 pt-1">
              <Button
                variant="outline"
                size="sm"
                onClick={handleFavorite}
                disabled={isLoading}
              >
                {isLoading ? (
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                ) : (
                  <Heart
                    className={cn(
                      "h-4 w-4 mr-2",
                      isFavorited && "fill-current"
                    )}
                  />
                )}
                {isFavorited ? "Favorited" : "Favorite"}
              </Button>
              <Button
                size="sm"
                className="bg-primary"
                onClick={handleDownload}
                disabled={isDownloading}
              >
                {isDownloading ? (
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                ) : (
                  <Download className="h-4 w-4 mr-2" />
                )}
                Download
              </Button>
            </div>
          </div>
        </div>
      </div>
      <div className="absolute inset-0 bg-background/60 backdrop-blur-xl -z-10" />
    </>
  );
}
