"use client";

import { Tweak, TweakType, TweakerProfile } from "@prisma/client";
import { Card } from "@/components/ui/card";
import { formatDistanceToNow } from "date-fns";
import {
  Download,
  Eye,
  Star,
  Calendar,
  User2,
  Heart,
  Loader2,
} from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import TweakTags from "@/components/TweakTags";
import { cn } from "@/lib/utils";
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { useRouter } from "next/navigation";
import { TweaksService } from "@/app/(dashboard)/_services/tweaksService";
import toast from "react-hot-toast";
import { useState } from "react";

interface TweakItemProps {
  tweak: Tweak & {
    authorProfile: TweakerProfile | null;
  };
  tweakID: string;
  userId: string | null;
  categoryName: string;
  tweakType: TweakType | null;
}

export default function TweakItem({
  tweak,
  tweakID,
  userId,
  categoryName,
  tweakType,
}: TweakItemProps) {
  const router = useRouter();
  const [isLoading, setIsLoading] = useState(false);
  const [isDownloading, setIsDownloading] = useState(false);
  const [downloadCount, setDownloadCount] = useState(
    Number(tweak.downloadCount || 0)
  );
  const isFavorited = tweak.savedUsers.includes(userId || "");

  const handleFavorite = async (e: React.MouseEvent) => {
    e.preventDefault();
    if (!userId) {
      toast.error("Please sign in to save tweaks");
      return;
    }

    try {
      setIsLoading(true);
      const result = await TweaksService.toggleSaveTweak(tweakID);

      if (result.error) {
        toast.error(result.error);
        return;
      }

      toast.success(
        isFavorited ? "Removed from favorites" : "Added to favorites"
      );
      router.refresh();
    } catch (error) {
      toast.error("Failed to update favorite status");
    } finally {
      setIsLoading(false);
    }
  };

  const handleDownload = async (e: React.MouseEvent) => {
    e.preventDefault();

    try {
      setIsDownloading(true);

      // Increment download count first
      const result = await TweaksService.incrementDownloadCount(tweakID);
      if (result.error) {
        console.error("Failed to increment download count:", result.error);
        toast.error("Failed to update download count");
        return;
      }

      // Update local state if increment was successful
      if (result.data) {
        setDownloadCount(Number(result.data.downloadCount || 0));
      }

      // Get file extension based on tweak type
      let fileExt = ".reg";
      let commentPrefix = ";";

      switch (tweak.tweak_type?.toLowerCase()) {
        case "batch":
          fileExt = ".bat";
          commentPrefix = "REM";
          break;
        case "powershell":
          fileExt = ".ps1";
          commentPrefix = "#";
          break;
        case "registry":
          fileExt = ".reg";
          commentPrefix = ";";
          break;
        default:
          fileExt = ".txt";
          commentPrefix = "#";
      }

      // Create warning message based on file type
      const warningMessage =
        fileExt === ".reg"
          ? `Windows Registry Editor Version 5.00\r\n\r\n`
          : "";

      const warning =
        `${warningMessage}${commentPrefix} ⚠️ WARNING ⚠️\r\n\r\n` +
        `${commentPrefix} BetterPerformance is not responsible for any misuse of the tweaks generated by this website.\r\n` +
        `${commentPrefix} These tweaks are automatically created as soon as you click the "Download" button.\r\n\r\n` +
        `${commentPrefix} IMPORTANT:\r\n` +
        `${commentPrefix} Before applying any tweak, please make sure to create a restore point.\r\n` +
        `${commentPrefix} This will allow you to revert changes in case you are not satisfied with the before/after effects of the tweak.\r\n\r\n` +
        `${commentPrefix} The services offered by BetterPerformance are COMPLETELY FREE.\r\n` +
        `${commentPrefix} However, we appreciate any donations you may want to make to help maintain the website and ensure its continuity.\r\n\r\n` +
        `${commentPrefix} It is STRICTLY FORBIDDEN to sell any of the tweaks generated by this website\r\n` +
        `${commentPrefix} or to commercialize any service related to the use of this platform.\r\n` +
        `${commentPrefix} If it is proven that a user is violating this rule, the following actions will be taken:\r\n\r\n` +
        `${commentPrefix}     Permanent ban of the user to prevent future access to the website.\r\n` +
        `${commentPrefix}     Legal actions against the user, if applicable.\r\n\r\n` +
        `${commentPrefix} COPYRIGHT NOTICE:\r\n` +
        `${commentPrefix} All copyright rights are reserved by BetterPerformance.\r\n` +
        `${commentPrefix} While some elements of the tweaks may not be 100% original to the author,\r\n` +
        `${commentPrefix} their development is entirely managed and created by BetterPerformance.\r\n\r\n` +
        `${commentPrefix} Enjoy the service, use it responsibly, and don't forget to create a restore point! 🙌\r\n\r\n`;

      // Create blob with warning and content
      const content = warning + (tweak.regedit || "");
      const blob = new Blob([content], { type: "text/plain" });

      // Create download link
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = `${tweak.title}${fileExt}`;

      // Then trigger download
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      window.URL.revokeObjectURL(url);

      toast.success("Download started");
      router.refresh();
    } catch (error) {
      console.error("Download error:", error);
      toast.error("Failed to download tweak");
    } finally {
      setIsDownloading(false);
    }
  };

  return (
    <div className="group">
      <Card className="border border-border/40 transition-all bg-secondary/20 duration-200 hover:border-primary/20 hover:bg-primary/[0.02]">
        <div className="p-3">
          {/* Header Section */}
          <div className="flex items-start gap-3">
            <div className="relative w-12 h-12 rounded-lg overflow-hidden flex-shrink-0">
              <Image
                src={tweak.icon_url || "/placeholder.svg"}
                alt={tweak.title}
                width={48}
                height={48}
                className="object-cover w-full h-full"
              />
            </div>
            <div className="flex-1 min-w-0">
              <div className="flex flex-col gap-1">
                <div className="min-w-0">
                  <Link
                    href={`/explore/${tweakID}`}
                    className="hover:underline inline-flex items-center gap-2"
                  >
                    <h3 className="font-semibold text-sm line-clamp-1">{tweak.title}</h3>
                  </Link>
                  <div className="flex gap-1 flex-wrap mt-0.5">
                    <TweakTags
                      categoryName={categoryName}
                      tweakType={tweakType}
                    />
                  </div>
                  <p className="text-xs text-muted-foreground line-clamp-2 mt-1 h-8">
                    {tweak.short_description}
                  </p>
                </div>
              </div>

              {/* Stats Section */}
              <div className="flex items-center flex-wrap gap-2 mt-2 text-xs text-muted-foreground">
                <div className="flex items-center gap-1">
                  <Download className="h-3 w-3" />
                  <span>{downloadCount}</span>
                </div>
                <div className="flex items-center gap-1">
                  <Star className="h-3 w-3" />
                  <span>{tweak.savedUsers.length}</span>
                </div>
                <div className="flex items-center gap-1">
                  <Eye className="h-3 w-3" />
                  <span>{tweak.viewCount}</span>
                </div>
                <div className="flex items-center gap-1">
                  <Calendar className="h-3 w-3" />
                  <span>
                    {formatDistanceToNow(new Date(tweak.updatedAt), {
                      addSuffix: true,
                    })}
                  </span>
                </div>
              </div>
            </div>
          </div>

          {/* Footer Section */}
          <div className="flex items-center justify-between mt-2 pt-2 border-t border-border/50">
            <Link
              href={`/tweaker/${tweak.authorProfile?.userId}`}
              className="flex items-center gap-2 hover:opacity-80 transition-opacity"
            >
              <Avatar className="h-5 w-5">
                <AvatarImage
                  src={
                    tweak.authorProfile?.customTheme &&
                      typeof tweak.authorProfile.customTheme === 'object' &&
                      'avatarUrl' in tweak.authorProfile.customTheme
                      ? (tweak.authorProfile.customTheme as { avatarUrl: string }).avatarUrl
                      : "/placeholder-avatar.svg"
                  }
                />
                <AvatarFallback className="text-[10px]">
                  {tweak.authorProfile?.username?.[0]?.toUpperCase() || "A"}
                </AvatarFallback>
              </Avatar>
              <div className="text-xs font-medium">
                {tweak.authorProfile?.username || "Anonymous"}
              </div>
            </Link>
            <div className="flex items-center gap-1.5">
              <Button
                variant="ghost"
                size="icon"
                className={cn(
                  "h-7 w-7 transition-colors",
                  isFavorited && "text-primary hover:text-primary/80"
                )}
                onClick={handleFavorite}
                disabled={isLoading}
              >
                {isLoading ? (
                  <Loader2 className="h-3.5 w-3.5 animate-spin" />
                ) : (
                  <Heart
                    className={cn("h-3.5 w-3.5", isFavorited && "fill-current")}
                  />
                )}
              </Button>
              <Button
                variant="outline"
                size="sm"
                className="h-7 px-2.5 text-xs border-primary/20 hover:bg-primary hover:text-primary-foreground transition-colors duration-200"
                onClick={handleDownload}
                disabled={isDownloading}
              >
                {isDownloading ? (
                  <Loader2 className="h-3 w-3 animate-spin mr-1" />
                ) : (
                  <Download className="h-3 w-3 mr-1" />
                )}
                Download
              </Button>
            </div>
          </div>
        </div>
      </Card>
    </div>
  );
}
